name: Windows RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Download Ngrok
        run: |
          curl -L https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -o ngrok.zip
          tar -xf ngrok.zip

      - name: Enable RDP
        run: |
          net user runneradmin Password123! /add
          net localgroup administrators runneradmin /add
          reg add "HKLM\System\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Start Ngrok Tunnel
        run: |
          .\ngrok authtoken 2yTGXjOucmtLbslj4gHvfhPMMtD_7WvugEqip6Y3Utun6Em4n
          start .\ngrok tcp 3389

      - name: Keep Alive
        run: timeout /t 999999
